workflows:
  upload_ios_metadata:
    name: Upload iOS metadata
    instance_type: mac_mini_m1
    max_build_duration: 45

    environment:
      xcode: 16.2
      groups:
        - appstore-connect
        - match
        - ios
      vars:
        IOS_BUNDLE_ID: com.solkovalproj.app
        APP_NAME: Highway Story

    scripts:
      - name: Print working dir & contents
        script: |
          echo "PWD: $(pwd)"
          ls -R

      - name: Install Ruby dependencies
        script: |
          bundle install
          gem install fastlane-plugin-appicon || true

      - name: Validate metadata directory structure
        script: |
          echo "===== Validating Metadata ====="
          # ... (далі твій код без змін)
          
      - name: Sync certificates via fastlane match
        script: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$MATCH_DEPLOY_KEY"
          bundle exec fastlane ios sync_certificates

      - name: Upload metadata via fastlane deliver
        script: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$MATCH_DEPLOY_KEY"
          bundle exec fastlane ios upload_metadata

    artifacts:
      - fastlane/logs/**/*
      - ~/Library/Logs/gym/**/*

    publishing:
      email:
        recipients:
          - $APPLE_EMAIL
        notify:
          success: true
          failure: true
